# Generated by Django 2.1.3 on 2019-01-19 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20190119_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTags',
            new_name='ArticleTag',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 5, 10, 31, 683810, tzinfo=utc)),
        ),
    ]
