# Generated by Django 2.1.3 on 2019-01-19 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 5, 0, 26, 93473, tzinfo=utc)),
        ),
    ]
